site_name: ANNOVAR Documentation
site_url: http://annovar.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/doc-ANNOVAR/
repo_name: GitHub
site_description: Documentation for ANNOVAR software
site_author: Kai Wang
site_favicon: favicon.ico
copyright: 2010-2015 ANNOVAR
google_analytics: ['UA-36723568-3', 'mkdocs.org']


docs_dir: docs
include_search: true
use_absolute_urls: true
# the line below is absolutely necessary (see https://github.com/rtfd/readthedocs.org/issues/1101 for explanation)
use_directory_urls: false

pages:
# User guide:
- ['index.md', 'ANNOVAR']
- ['startup.md', 'Quick Start up Guide']
- ['download.md', 'Download ANNOVAR']
- ['input.md', 'Prepare Input Files']
- ['gene.md', 'Gene-based Annotation']
- ['region.md', 'Region-based Annotation']
- ['filter.md', 'Filter-based annotation']
- ['accessory.md', 'Using Accessary Programs']
- ['faq.md', 'FAQ']
- ['contributing.md', 'Contribute to doc-ANNOVAR']




# Articles
- ['articles/VCF.md', 'Articles', 'VCF processing guide']
- ['articles/dbSNP.md', 'Articles', 'Assigning dbSNP identifiers']

