site_name: ANNOVAR Documentation
site_url: http://annovar.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/doc-ANNOVAR/
repo_name: GitHub
site_description: Documentation for ANNOVAR software
site_author: Kai Wang
site_favicon: favicon.ico
copyright: 2010-2015 ANNOVAR


docs_dir: docs
include_search: true
use_absolute_urls: true
# the line below is absolutely necessary (see https://github.com/rtfd/readthedocs.org/issues/1101 for explanation)
use_directory_urls: false

pages:
# User guide:
- ['index.md', 'ANNOVAR']
- ['startup.md', 'Quick Start Up Guide']
- ['download.md', 'Download ANNOVAR']
- ['input.md', 'Prepare Input Files']
- ['gene.md', 'Gene-based Annotation']
- ['region.md', 'Region-based Annotation']
- ['filter.md', 'Filter-based annotation']
- ['accessory.md', 'Using Accessary Programs']

- ['misc/whatsnew.md', 'Misc', 'What's New']
- ['misc/faq.md', 'Misc', 'FAQ']
- ['misc/contributing.md', 'Misc', 'Contribute to ANNOVAR']


# Articles
- ['articles/VCF.md', 'Articles', 'VCF processing guide']
- ['articles/dbSNP.md', 'Articles', 'Assigning dbSNP identifiers']

