site_name: ANNOVAR Documentation
site_url: http://annovar.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/doc-ANNOVAR/
repo_name: GitHub
site_description: Documentation for ANNOVAR software
site_author: Kai Wang
site_favicon: favicon.ico
copyright: 2010-2015 ANNOVAR
google_analytics: ['UA-36723568-3', 'mkdocs.org']


docs_dir: docs
include_search: true
use_absolute_urls: true
# the line below is absolutely necessary (see https://github.com/rtfd/readthedocs.org/issues/1101 for explanation)
use_directory_urls: false

pages:
# Introduction:
- ['index.md', 'ANNOVAR']
- ['01_Quick_Start.md', 'Release Notes']
- ['02_Download.md', 'Download ANNOVAR']
- ['03_Prepare_Input_File.md', 'Prepare Input Files']


# Articles
- ['articles/index.md', '**HIDDEN**']
- ['articles/VCF.md', 'Articles', 'VCF processing']
- ['articles/dbSNP.md', 'Articles', 'dbSNP processing']

