site_name: ANNOVAR Documentation
site_url: http://annovar.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/doc-ANNOVAR/
repo_name: GitHub
site_description: Documentation for ANNOVAR software
site_author: Kai Wang, et al
site_favicon: favicon.ico
copyright: 2010-2015 ANNOVAR
google_analytics: ['UA-48623707-1', 'www.openbioinformatics.org/annovar']

docs_dir: .
include_search: true
#use_absolute_urls: true
# the line below is absolutely necessary (see https://github.com/rtfd/readthedocs.org/issues/1101 for explanation)
#use_directory_urls: false

pages:
# for strange reasons I can only put max of 7 items below for building to pass
- ['index.md', 'ANNOVAR']

# User Guide
- ['user-guide/download.md', 'User Guide', 'Download ANNOVAR']
- ['user-guide/startup.md', 'User Guide', 'Quick Start-Up Guide']
- ['user-guide/input.md', 'User Guide', 'Prepare Input Files']
- ['user-guide/gene.md', 'User Guide', 'Gene-based Annotation']
- ['user-guide/region.md', 'User Guide', 'Region-based Annotation']
- ['user-guide/filter.md', 'User Guide', 'Filter-based Annotation']

# Misc
- ['misc/accessory.md', 'Misc', 'Accessoary Programs']
- ['misc/faq.md', 'Misc', 'FAQ']
- ['misc/whatsnew.md', 'Misc', 'What is New']
- ['misc/version_history.md', 'Misc', 'Version History']
- ['misc/credit.md', 'Misc', 'Credit']
- ['misc/contributing.md', 'Misc', 'How to Contribute']


# Articles
- ['articles/VCF.md', 'Articles', 'VCF Processing Guide']
- ['articles/dbSNP.md', 'Articles', 'Assigning dbSNP Identifiers']
- ['articles/wANNOVAR.md', 'Articles', 'wANNOVAR Tutorial']

